### ISSUE TITLE
[type-scripts-build] failing to build with `rxjs` set as a peerDependency

### ISSUE THREAD

**Issue by ncphillips** [ncphillips/create-typescript-package#20]
I'm trying to switch [create-observable-thunk](/forestryio/create-observable-thunk) to Typescript, and build it with create-typescript-project.

Unfortunately building doesn't work, and outputs the following:

```yarn run v1.3.2
$ type-scripts-build
Creact Typescript Package – Build
        Typescript Version:  2.6.2
        Package Name:  create-observable-thunk
        External Dependencies:  [ 'redux', 'redux-thunk', 'rxjs' ]
(node:613) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: "version" is a required argument.
(node:613) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ncphillips** [comment]
I managed to get the full error from rollup:

```
Error: "version" is a required argument.
    at Object.getArg (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:14741:11)
    at new BasicSourceMapConsumer (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:15879:22)
    at new SourceMapConsumer$1 (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:15607:7)
    at Module.getOriginalLocation (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:17001:23)
    at Module.error (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:17013:33)
    at Module.trace (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:17149:22)
    at ModuleScope.findVariable (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:14293:28)
    at FunctionScope.Scope.findVariable (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:11691:69)
    at Scope.findVariable (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:11691:69)
    at Node.MemberExpression.bind (/Users/nolan/Code/projects/create-typescript-package/demo1/node_modules/rollup/dist/rollup.js:13233:39)
```

This [post on stackoverflow](https://stackoverflow.com/questions/47979169/error-version-is-a-required-argument-while-building-with-rollup) suggests it may have something to do with source-maps?
